spring:
  application:
    name: hodor-scheduler
  profiles:
    active: core

hodor:
  netServer:
    host: 127.0.0.1
    port: 8080
  registry:
    servers: 127.0.0.1:2181
    namespace: "hodor-test"