spring:
  application:
    name: hodor-scheduler
  output:
    ansi:
      enabled: always
  profiles:
    active: core

logging:
  level:
    root: INFO
  file: log/hodor-scheduler.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) [%yellow(%thread)] %green(%logger{15}) : %msg%n'
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS}  %highlight(%-5level) [%yellow(%thread)] %green(%logger{15}) : %msg%n'

hodor:
  netServer:
    host: 127.0.0.1
    port: 8080
  registry:
    servers: 127.0.0.1:2181
    namespace: "hodor-test"